import{state,$,loopLength,beat,beats}from'./state.js';
import{ensureMedia,attachPreview}from'./camera.js';
import{saveTrack,loadTracks,deleteTrack}from'./storage.js';
import{startMetronome,stopMetronome}from'./metronome.js';
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
function renderViewer(camera=false){const v=$('viewer');v.className=`viewer ${state.layout}`;v.innerHTML='';state.tracks.forEach((t,i)=>{const c=document.createElement('div');c.className=`cell ${i===state.selected?'selected':''}`;c.innerHTML=`<video muted playsinline loop></video><div class="label">SPUR ${i+1}</div><div class="empty">SPUR ${i+1}</div>`;c.onclick=()=>{state.selected=i;renderAll(true)};v.appendChild(c);const vid=c.querySelector('video'),empty=c.querySelector('.empty');if(t.url){vid.src=t.url;vid.play().catch(()=>{});empty.hidden=true}else if(camera&&i===state.selected)attachPreview(vid).then(()=>empty.hidden=true).catch(()=>{})})}
function renderTracks(){const root=$('tracks');root.innerHTML='';state.tracks.forEach((t,i)=>{const r=document.createElement('div');r.className='track';r.innerHTML=`<div class="trackSide"><div class="trackName">${t.name}</div><button class="m ${t.mute?'on':''}">M</button><button class="s ${t.solo?'on':''}">S</button><button class="d">🗑</button></div><div class="lane"><div class="clip ${t.url?'show':''}">${t.url?`<video src="${t.url}" muted playsinline></video>`:''}<span>${t.name}</span></div></div>`;r.onclick=()=>{state.selected=i;renderAll(true)};r.querySelector('.m').onclick=e=>{e.stopPropagation();t.mute=!t.mute;renderTracks()};r.querySelector('.s').onclick=e=>{e.stopPropagation();t.solo=!t.solo;renderTracks()};r.querySelector('.d').onclick=async e=>{e.stopPropagation();if(t.url)URL.revokeObjectURL(t.url);Object.assign(t,{blob:null,url:null,mute:false,solo:false});await deleteTrack(i);renderAll(true);toast(`Spur ${i+1} gelöscht`)};if(i===state.selected)r.style.outline='1px solid #775cff';root.appendChild(r)})}
function renderAll(camera=false){renderViewer(camera);renderTracks()}
async function record(){if(state.recording)return;try{const stream=await ensureMedia();state.chunks=[];const types=['video/webm;codecs=vp8,opus','video/webm'];const mime=types.find(x=>MediaRecorder.isTypeSupported(x));state.recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.recorder.ondataavailable=e=>e.data.size&&state.chunks.push(e.data);state.recorder.onstop=async()=>{const blob=new Blob(state.chunks,{type:state.recorder.mimeType||'video/webm'});const t=state.tracks[state.selected];if(t.url)URL.revokeObjectURL(t.url);t.blob=blob;t.url=URL.createObjectURL(blob);await saveTrack(state.selected,blob);state.recording=false;$('record').classList.remove('recording');renderAll(false);toast(`${t.name} gespeichert`)};state.recording=true;$('record').classList.add('recording');state.recorder.start(200);toast(`Aufnahme ${state.tracks[state.selected].name}`);setTimeout(()=>{if(state.recorder?.state==='recording')state.recorder.stop()},loopLength()*1000)}catch(e){console.error(e);toast('Kamera/Mikrofon nicht verfügbar')}}
function play(){const vids=[...document.querySelectorAll('.cell video')];if(!state.tracks.some(t=>t.url))return toast('Noch keine Spur aufgenommen');state.playing=true;state.start=performance.now();vids.forEach((v,i)=>{if(state.tracks[i].url&&!state.tracks[i].mute){v.currentTime=0;v.play().catch(()=>{})}});startMetronome();animate()}
function stop(){state.playing=false;stopMetronome();document.querySelectorAll('.cell video').forEach(v=>{if(v.src){v.pause();try{v.currentTime=0}catch{}}});$('counter').textContent='1.1';$('playhead').style.left='var(--side)'}
function animate(){if(!state.playing)return;const p=((performance.now()-state.start)/1000)%loopLength(),b=Math.floor(p/beat()),bar=Math.floor(b/beats())+1,bt=b%beats()+1;$('counter').textContent=`${bar}.${bt}`;const w=$('timeline').clientWidth-82;$('playhead').style.left=`${82+p/loopLength()*w}px`;requestAnimationFrame(animate)}
document.querySelectorAll('.layoutbar button').forEach(b=>b.onclick=()=>{state.layout=b.dataset.layout;document.querySelectorAll('.layoutbar button').forEach(x=>x.classList.toggle('on',x===b));renderViewer(true)});$('permission').onclick=()=>ensureMedia().then(()=>renderViewer(true)).catch(()=>toast('Berechtigung verweigert'));$('record').onclick=record;$('play').onclick=play;$('stop').onclick=stop;$('metro').onclick=()=>{state.metro=!state.metro;$('metro').classList.toggle('active',state.metro);toast(state.metro?'Metronom an':'Metronom aus')};
window.addEventListener('load',async()=>{const blobs=await loadTracks().catch(()=>[]);blobs.forEach((b,i)=>{if(b){state.tracks[i].blob=b;state.tracks[i].url=URL.createObjectURL(b)}});renderAll(true);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});
